services:

  shopcart:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: shopcart

    restart: unless-stopped

    ports:
      - "80:80"

    env_file:
      - .env

    volumes:
      - shopcart-storage:/var/www/html/storage

    networks:
      - shopcart-network

networks:
  shopcart-network:

volumes:
  shopcart-storage:
