services:

  pasaria:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: pasaria
    restart: unless-stopped

    ports:
      - "80:80"

    env_file:
      - .env

    volumes:
      - pasaria-storage:/var/www/html/storage
      - ./.env:/var/www/html/.env

    networks:
      - pasaria-network

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/up"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s

networks:
  pasaria-network:

volumes:
  pasaria-storage:
